### ISSUE TITLE
is getServerParams really necessary?

### ISSUE THREAD

**Issue by oscarotero** [php-fig/http-message#14]
I wonder whether or not `IncomingRequestInterface::getServerParams` is required. This is an interface for manage http messages, and $_SERVER is only an implementation of php to provide some values like http headers, requests method, client ip, etc, but all this information is available using other functions (getHeader, getMethod, etc). So this duplicates the way to access to the same information (for example: `$request->getHeader('Accept')` and `$request->getServerParams()['HTTP_ACCEPT']`).

**Comment by weierophinney** [comment]
It is necessary, as it allows a consumer of the interface to aggregate and perform calculations on information gleaned from the server environment. Yes, some of that information is duplicated, but there are large swaths that are not; the information can include information injected by the web server or PaaS provider as well, which may not be accessible any other way, or even artifacts like the `SCRIPT_NAME` or `PHP_SELF`.

One use case we identified recently has to do with how different frameworks identify the "base path" of a request; different frameworks do this differently, but get their information from different sources in `$_SERVER`.

So, yes, it needs to be there.

**Comment by oscarotero** [comment]
Well, IMHO, if an object representing a http message needs a method to return other diferent data (or the same data in raw mode), is because something is wrong.
The data provided by the server is not about a http message, it's about the server itself and the sofware used to run this server. If I need to know the path of my front controller, I don't think `$currentRequest->getServerParams()['SCRIPT_FILENAME']` is a good place to get it from. This should be managed separately (as the single responsibility principle says). Maybe a `Server` class to manage this information is a better approach (just an idea).

**Comment by weierophinney** [comment]
@oscarotero The consensus on the list is that this needs to be part of the `ServerRequest`, in order to simplify and codify what frameworks are already implementing.
