### ISSUE TITLE
Doubts (Question?)

### ISSUE THREAD

**Issue by pine3ree** [php-fig/http-message#30]
I was wondering about the MUST requirements imposed on the with{...} methods.

"This method MUST retain the state of the current instance, and return a new instance that contains the specified user information."

In my opinion if the with{} method doesn't change the state of the current instance, cloning should be avoided and the method should return the same instance. This would avoid unnecessary overhead while still preserving immutability.

**Comment by yoosefi** [comment]
At first glance this might seem true, but PHP is copy-on-write. Chaining clone operations has very little overhead.

**Comment by pine3ree** [comment]
Yes i understand that, but i believe that in principle if the final goal is to preserve the immutability of value objects, there is really no need to create identical clones, which by their own nature are immutable as well.
A less strict MUST as "...and return a new instance that contains the specified user information IF|WHEN a state change is likely to occur..." would allow both kinds of implementation 1) always clone - as in phly/http and slim-3-dev 2) clone only in case of state change.

**Comment by harikt** [comment]
@pine3ree this has been already talked over the groups. And now is on vote.

So you should not expect anything to change :) .

**Comment by yoosefi** [comment]
Checking for a potential state change could introduce more overhead than the cloning itself.

**Comment by pine3ree** [comment]
Not necessarily. 
Consider the UriInterface implementation in phly/http and methods withPort() and withScheme().
I believe that a simple identity check (===) for the instance scheme|port property and the method scheme|port parameter will introduce less overhead than full cloning.

we can skip cloning on those simpler cases and shortcircuit returning $this.

I am not saying we MUST always check for a possible state change, only that we are allowed to do that in simpler cases.  

kindly.

**Comment by yoosefi** [comment]
There's nothing stopping you from doing this under the hood. I just don't think things that are rarely changed (like the schema) will be changed often, thus not justifying the extra check and added n-path complexity. These are interfaces after all, the implementation is up to you. This would essentially be you reinventing copy-on-write.

**Comment by yoosefi** [comment]
I don't foresee someone's library switching between HTTP and HTTPS a hundred times per invocation, for example. Shaving off a redundant schema change would not save you very much more than some microseconds. It's kind of a micro-optimization at that point and adds programmer-overhead not worth the savings.

**Comment by yoosefi** [comment]
You should really be worried more about I/O and inefficient SQL in the grander scale of optimizing your application. Those are the real bottlenecks. Not a few redundant op-codes.

**Comment by pine3ree** [comment]
Everybody optimizes sql and i/o and try to use more efficient functions.
But that's not the point. This is not only about optimization, but about being forced to perfom operations that actually do nothing. 
What i find avoidable is cloning an object to get an identical copy (for every with|without{...} method). I don't mean to force you not to clone, but allow you not to. So far the specs force you to always clone.

"This method MUST be implemented in such a way as to retain the immutability of the message."

Using just this specification, without the "MUST return" part, would allow the developer to choose how to implement (to clone or not to clone) the method.

**Comment by yoosefi** [comment]
If you read more into that spec, it only goes so far as to mean "don't change the state of the instance."

So, if the `with` won't change the state, you're not violating the spec by returning the same instance.

**Comment by yoosefi** [comment]
The immutability should be maintained because something in a higher scope might need that original state. If you change the state of an object then other things that rely on that state will break. That's the idea behind the `with` idiom

**Comment by yoosefi** [comment]
Interfaces cannot and should not place demands on the specific code used to fulfill behavior. An interface is only an *expected* behavior.

**Comment by pine3ree** [comment]
Not according to the docblocks:

UriInterface
     * This method MUST retain the state of the current instance, and return
     * a new instance that contains the specified query string.

MessageInterface
     * This method MUST be implemented in such a way as to retain the
     * immutability of the message, and MUST return a new instance that

all (with|withput){...} methods are required to return a new instance

**Comment by yoosefi** [comment]
Oh. Well, that "new instance" bit shouldn't be there. I see your point there.

**Comment by yoosefi** [comment]
But, again, this is splitting hairs. Just clone and forget about it. PHP is efficient with copy-on-write. When you clone an object, you are not actually duplicating it in memory. PHP just makes a new variable with all the properties shared with the old one and starts teasing out copies when you change something.

**Comment by pine3ree** [comment]
Not always.
Suppose you need to parse body data in a few middlewares and suppose  middlewares passes a cloned request object to the next middleware.

That(those) next middleware(s) will have to parse the request body all over again again.

if a with|out method that doesn't change anything could return the same instance, the body would be already parsed and ready.

**Comment by yoosefi** [comment]
I don't follow what you're saying. A clone is conceptually a direct copy. If the message body is already parsed in the original, it will be parsed in the clone.

**Comment by pine3ree** [comment]
Yes, but if you use withBody() method the parsed body would probably be cleared, but if you pass the same stream instance ther is no point in doing that, so either you check for this identity and do not clear the parsed body or simply (and simpler) return $this in every case when with{} do not mean affect the state.

**Comment by yoosefi** [comment]
Whether or not a hypothetical parse tree for the body would be wiped out is up to the implementation.

Again, returning a pure clone will preserve any such properties. Anything done to properties after cloning is a downstream issue.

**Comment by krzysiekpiasecki** [comment]
@pine3ree Checking if state has changed is not necessary. Developers use 'withX' method to create new instance.

**Comment by pine3ree** [comment]
@krzysiekpiasecki 
oh sorry, i forgot to close the issue long time ago....
best regards
