### ISSUE TITLE
MessageInterface::withHeader()

### ISSUE THREAD

**Issue by KpuTuK** [php-fig/http-message#60]
Hi, 
### MessageInterface::withHeader()
> Return an instance with the provided value **replacing** the specified header

And how to be with
```Set-cookie: name=cookie1; Set-cookie: name=cookie2;```

???

**Comment by JoeBengalen** [comment]
You looking for `withAddedHeader()`? 
https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L150

**Comment by KpuTuK** [comment]
Thank you.
Just I'm not translated
