### ISSUE TITLE
Suggestion: Remove StreamableInterface::__toString

### ISSUE THREAD

**Issue by cboden** [php-fig/http-message#7]
> This method MUST attempt to seek to the beginning of the stream before reading data and read the stream until the end is reached.

Not all streams are seekable. A stream underneath an HTTP/1.1 connection that is chunked would not be seekable nor have a known end. `__toString` is not able to throw an exception. 

I would recommend letting the user explicitly call `isSeekable` followed by `getContents`.

**Comment by cboden** [comment]
ping @weierophinney

Thoughts? Did I post this concern in the wrong forum?

**Comment by weierophinney** [comment]
@cboden this works -- though the actual spec is in php-fig/fig-standards, which is likely why I didn't see the original feedback.

In the case of a non-seekable string, a `__toString()` implementation would need to return from the current position to the end of data. Can you send a PR against the php-fig/fig-standards repo with that change? When you do, prefix the PR with `[PSR-7]` so I'll spot it easily to review.

Thanks!
