### ISSUE TITLE
Introduce an UPGRADE file

### ISSUE THREAD

**Issue by egeloen** [php-fig/http-message#8]
Hey!

I'm currently maintaining a library around this standard but it seems some BC breaks have been introduced without real documentation about them. IMHO, it would be really appreciated to list them somewhere in order to more easily upgrade our libraries/apps.

What do you think?

**Comment by evert** [comment]
I wouldn't count it too much. PSR-7 is not a standard yet. What you're looking at is a work in progress, and it would be foolish to rely on the API.

**Comment by egeloen** [comment]
Let's close it as it will not happen.
